# Supabase Project Configuration
# Project: jbqljjyctbsyawijlxfa

project_id = "jbqljjyctbsyawijlxfa"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 5000

[db]
port = 54322
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
port = 54434
max_events_per_second = 100

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1"

[storage]
enabled = true
port = 5005
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "https://app.footylabs.ai/"
additional_redirect_urls = [
  "https://footylabs.vercel.app/auth/update-password",
  "https://app.footylabs.ai/auth/update-password", 
  "https://app.footylabs.ai/auth/callback",
  "http://localhost:3000/auth/callback",
  "https://app.footylabs.ai/*",
  "http://localhost:3000/*"
]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true
secure_password_change = false
max_frequency = "1m0s"
otp_length = 6
otp_expiry = 86400

[auth.mfa]
max_enrolled_factors = 10

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true

[auth.rate_limit]
anonymous_users = 30
token_refresh = 150
sign_in_sign_ups = 60
token_verifications = 30
email_sent = 2
sms_sent = 30

[analytics]
enabled = false
port = 54327
vector_port = 54328

# Local development overrides
[local]
# Use these settings when running locally with `supabase start`
inbucket_port = 54324  # Email testing
edge_runtime_port = 54330  # Edge functions