-- Migration: Player Reviews System
-- Adds is_dummy flag to club_reviews and creates agent_reviews table
-- Uses player_profiles table (not profiles) for linking reviews to players

-- 1. Add is_dummy column to club_reviews (default true for existing rows)
ALTER TABLE club_reviews
ADD COLUMN IF NOT EXISTS is_dummy BOOLEAN DEFAULT false;

-- Mark all existing reviews as dummy data
UPDATE club_reviews SET is_dummy = true WHERE is_dummy IS NULL;

-- Add player_profile_id to club_reviews to track who wrote the review
-- Links to player_profiles which has transfermarkt_player_id
ALTER TABLE club_reviews
ADD COLUMN IF NOT EXISTS player_profile_id UUID REFERENCES player_profiles(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_club_reviews_player_profile_id ON club_reviews(player_profile_id);
CREATE INDEX IF NOT EXISTS idx_club_reviews_is_dummy ON club_reviews(is_dummy);

-- 2. Create agent_reviews table
CREATE TABLE IF NOT EXISTS agent_reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agent_name TEXT NOT NULL,
  player_profile_id UUID NOT NULL REFERENCES player_profiles(id) ON DELETE CASCADE,
  overall_rating INTEGER NOT NULL CHECK (overall_rating >= 1 AND overall_rating <= 5),
  comment TEXT,
  category_ratings JSONB,
  is_dummy BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Add indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_agent_reviews_agent_name ON agent_reviews(agent_name);
CREATE INDEX IF NOT EXISTS idx_agent_reviews_player_profile_id ON agent_reviews(player_profile_id);
CREATE INDEX IF NOT EXISTS idx_agent_reviews_is_dummy ON agent_reviews(is_dummy);

-- Enable RLS on agent_reviews
ALTER TABLE agent_reviews ENABLE ROW LEVEL SECURITY;

-- RLS Policies for agent_reviews
-- Anyone can view reviews
CREATE POLICY "Anyone can view agent reviews" ON agent_reviews
  FOR SELECT USING (true);

-- Players can insert their own reviews (player_profile_id must match their auth.uid)
CREATE POLICY "Players can insert their own agent reviews" ON agent_reviews
  FOR INSERT TO authenticated
  WITH CHECK (auth.uid() = player_profile_id);

-- Players can update their own reviews
CREATE POLICY "Players can update their own agent reviews" ON agent_reviews
  FOR UPDATE TO authenticated
  USING (auth.uid() = player_profile_id);

-- RLS Policies for club_reviews (adding player-specific policies)
CREATE POLICY "Players can insert their own club reviews" ON club_reviews
  FOR INSERT TO authenticated
  WITH CHECK (auth.uid() = player_profile_id);

CREATE POLICY "Players can update their own club reviews" ON club_reviews
  FOR UPDATE TO authenticated
  USING (auth.uid() = player_profile_id);

-- Comment explaining the category_ratings structure for agent_reviews
COMMENT ON COLUMN agent_reviews.category_ratings IS 'JSON object with keys: Communication, Professionalism, Career Guidance, Contract Negotiation, Transparency. Each value is 1-5.';
