name: Test on Develop

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10
          run_install: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run linter
        run: pnpm run lint
        continue-on-error: true # Remove when linting is fixed

      - name: Run tests
        run: pnpm test
        continue-on-error: true # Remove when tests are added

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Validate migrations locally
        run: |
          echo "Testing migrations in local Supabase..."
          # Start local Supabase
          supabase start
          # Test migrations locally
          supabase db reset
          # If migrations work locally, they'll work in production
          supabase stop

      - name: Notify success
        if: success()
        run: echo "✅ Develop branch tests passed!"
        
      - name: Notify failure
        if: failure()
        run: echo "❌ Develop branch tests failed!"