name: Deploy to Staging

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.STAGING_DB_PASSWORD }}
      SUPABASE_PROJECT_ID: ${{ secrets.STAGING_PROJECT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
        continue-on-error: true # Remove this when tests are set up

      - name: Run linter
        run: npm run lint

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Link Supabase project
        run: supabase link --project-ref ${{ secrets.STAGING_PROJECT_ID }}

      - name: Run migrations
        run: supabase db push

      - name: Generate TypeScript types
        run: |
          supabase gen types typescript --project-id ${{ secrets.STAGING_PROJECT_ID }} > lib/supabase/database.types.ts
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add lib/supabase/database.types.ts
          git diff --staged --quiet || git commit -m "chore: update database types [skip ci]"
          git push

      - name: Deploy Edge Functions
        run: supabase functions deploy
        continue-on-error: true # Enable when edge functions exist

      - name: Notify success
        if: success()
        run: echo "✅ Staging deployment successful!"
        
      - name: Notify failure
        if: failure()
        run: echo "❌ Staging deployment failed!"